<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_appliedFilterPills</name>
   <tag></tag>
   <elementGuidId>7a8edd6f-b6cf-47d1-a289-8fa07642becf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-tag.css-1bkhbmc.app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(), 'Difilter berdasarkan')]/following-sibling::span[not(contains(text(), 'Hapus'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9861aaf4-670f-4fe8-b98d-7cfa49235b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-click</name>
      <type>Main</type>
      <value>gostr:/lzdse.result.filter;locaid:dx</value>
      <webElementGuid>625f0582-5945-4780-9bee-eacdb7dd5c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tag css-1bkhbmc app</value>
      <webElementGuid>08bb8447-c95d-423f-9ef3-f220e86b9b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.searchlist.0.</value>
      <webElementGuid>fb654754-1e80-4b1d-b45b-4babad2be6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price: 100000-3000000</value>
      <webElementGuid>2679a179-02a3-4449-a25e-8ec4cafe499c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;FWSEp&quot;]/div[@class=&quot;ant-row FrEdP css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-24 css-1bkhbmc app&quot;]/div[@class=&quot;ant-row css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-20 ant-col-push-4 Jv5R8 css-1bkhbmc app&quot;]/div[@class=&quot;pmGuc&quot;]/span[@class=&quot;ant-tag css-1bkhbmc app&quot;]</value>
      <webElementGuid>996194d4-80c3-4ddc-9919-cb52cc5a0422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/span[2]</value>
      <webElementGuid>ba7388bc-f04a-4a3c-a735-a4d7663b6e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Difilter berdasarkan:'])[1]/following::span[1]</value>
      <webElementGuid>ff718fea-72db-46bd-bd42-b5f46e891318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat:'])[1]/following::span[4]</value>
      <webElementGuid>0cb42b9d-638c-4016-ba74-0adb65e8f206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus semua'])[1]/preceding::span[2]</value>
      <webElementGuid>bd7bbf50-5239-4e7b-bac1-b44c14baa8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Price']/parent::*</value>
      <webElementGuid>3e5cf388-34a1-4c31-82a9-37bfe3d01f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>77dd13eb-21aa-45dc-991a-f6c3082a2552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Price: 100000-3000000' or . = 'Price: 100000-3000000')]</value>
      <webElementGuid>8a420293-2af2-4d82-9488-7e2162f2926a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
