<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSearch</name>
   <tag></tag>
   <elementGuidId>fda495e1-ec03-4121-9e46-5b35c13cfdfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class, 'search-box__search')]//a[contains(text(),'Cari')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.search-box__button--1oH7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18aedd41-aa11-4d8d-b370-e907dac01555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.lazada.co.id/catalog/?q=</value>
      <webElementGuid>fb432734-62f5-4f46-9a3a-2ab36171c5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box__button--1oH7</value>
      <webElementGuid>28213a94-56e2-486d-ace6-e16569799d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c4504e67-d096-4ec5-a740-0993612f7335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-click</name>
      <type>Main</type>
      <value>gostr=/lzdpub.header.search;locaid=d_go</value>
      <webElementGuid>f73eea3e-3b80-4ad0-b42c-749d6c188565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>73e88662-de67-4db6-ae63-406e3993a341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>742fd39d-2a7b-4aa3-9809-13ed062abfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>5cca13c1-01bd-4f71-9fc3-65b67415ba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topActionHeader&quot;)/div[@class=&quot;lzd-header-content&quot;]/div[@class=&quot;lzd-logo-bar home&quot;]/div[@class=&quot;logo-bar-content header-content&quot;]/div[@class=&quot;lzd-nav-search&quot;]/div[@class=&quot;layout-search-box--qK-K&quot;]/form[1]/div[@class=&quot;search-box--2I2a&quot;]/div[@class=&quot;search-box__search--2fC5&quot;]/a[@class=&quot;search-box__button--1oH7&quot;]</value>
      <webElementGuid>8b95ad7a-d5a6-44fe-9812-50e4fc12647d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topActionHeader']/div/div[2]/div/div[2]/div/form/div/div[2]/a</value>
      <webElementGuid>63f530f1-8236-436d-ac38-bccc823e1e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari')]</value>
      <webElementGuid>419e1d05-33d2-47e8-b55e-b8ae0f77238e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Lazada App Sekarang'])[1]/preceding::a[7]</value>
      <webElementGuid>a2b48ed8-173e-4029-abd8-0870e72ce484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nikmati Berbagai Voucher'])[1]/preceding::a[7]</value>
      <webElementGuid>f1ff3eda-5f10-4b42-9ea0-c5ce3250d666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>cbcb6df2-1b00-4498-9f77-4fa7ce1d7aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.lazada.co.id/catalog/?q=')]</value>
      <webElementGuid>c6f0404d-6150-45e6-9eb2-4b0627a7e748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>e97f3063-e4b2-40ec-8cce-477bcce09ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.lazada.co.id/catalog/?q=' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>ac241139-1d04-4083-9e08-195578880c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
