<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spaceBannersSlide</name>
   <tag></tag>
   <elementGuidId>25cc8cda-5635-41e8-af8d-a6168051feaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='banner-container-inner']//div[@class='swiper-slide']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-active > a.pc-custom-link.pc-each-banner-container > div.common-img > picture > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7ef0bc86-f803-425a-8774-6fa1ed95747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.lazcdn.com/us/media/ac93ee936575c04970026eddface8c20-1976-688.jpg_2200x2200q80.jpg</value>
      <webElementGuid>5720abd3-e4c3-4fa4-9885-acca20311f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.homepage.7290503930.i0.1e42600dCtO4HB</value>
      <webElementGuid>3c85083d-a2c2-41cd-ad40-8422839aff9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7290503930&quot;)/div[1]/div[@class=&quot;pc-custom-link pc-banner-slider-container&quot;]/div[@class=&quot;banner-container-inner&quot;]/div[@class=&quot;swiper-wrap&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/a[@class=&quot;pc-custom-link pc-each-banner-container&quot;]/div[@class=&quot;common-img&quot;]/picture[1]/img[1]</value>
      <webElementGuid>7dbb02ec-bf36-474d-bdac-3615e8410933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7290503930']/div/div/div/div/div/div/div[5]/a/div/picture/img</value>
      <webElementGuid>8ed06361-4b32-4018-8618-8cc39147b6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://img.lazcdn.com/us/media/ac93ee936575c04970026eddface8c20-1976-688.jpg_2200x2200q80.jpg')]</value>
      <webElementGuid>f3206fee-3806-4291-8156-6a416b129f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/picture/img</value>
      <webElementGuid>44c25b05-163c-406f-bc4f-fd9a250033b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.lazcdn.com/us/media/ac93ee936575c04970026eddface8c20-1976-688.jpg_2200x2200q80.jpg']</value>
      <webElementGuid>1d39549f-a7f4-4789-9765-14c4ebd98d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
